//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotInitial.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotInitial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Workshop Language.
        /// </summary>
        public static string applicationDisplayName {
            get {
                return ResourceManager.GetString("applicationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rwl.
        /// </summary>
        public static string fileExtension {
            get {
                return ResourceManager.GetString("fileExtension", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap image0 {
            get {
                object obj = ResourceManager.GetObject("image0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lear.
        /// </summary>
        public static string menuEditClear {
            get {
                return ResourceManager.GetString("menuEditClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string menuEditCopy {
            get {
                return ResourceManager.GetString("menuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string menuEditCut {
            get {
                return ResourceManager.GetString("menuEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string menuEditPaste {
            get {
                return ResourceManager.GetString("menuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_references....
        /// </summary>
        public static string menuEditPreferences {
            get {
                return ResourceManager.GetString("menuEditPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string menuEditRedo {
            get {
                return ResourceManager.GetString("menuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string menuEditUndo {
            get {
                return ResourceManager.GetString("menuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string menuFile {
            get {
                return ResourceManager.GetString("menuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string menuFileClose {
            get {
                return ResourceManager.GetString("menuFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string menuFileExit {
            get {
                return ResourceManager.GetString("menuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string menuFileNew {
            get {
                return ResourceManager.GetString("menuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string menuFileOpen {
            get {
                return ResourceManager.GetString("menuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Set_up....
        /// </summary>
        public static string menuFilePageSetup {
            get {
                return ResourceManager.GetString("menuFilePageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print....
        /// </summary>
        public static string menuFilePrint {
            get {
                return ResourceManager.GetString("menuFilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string menuFileSave {
            get {
                return ResourceManager.GetString("menuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string menuFileSaveAs {
            get {
                return ResourceManager.GetString("menuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string menuHelpAbout {
            get {
                return ResourceManager.GetString("menuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string menuTools {
            get {
                return ResourceManager.GetString("menuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Robots&gt;
        ///	&lt;Robot&gt;
        ///		&lt;DisplayName&gt;Lynx Robot 1&lt;/DisplayName&gt;
        ///		&lt;HostName&gt;robot1.csem.flinders.edu.au&lt;/HostName&gt;
        ///		&lt;IPAddress&gt;&lt;/IPAddress&gt;
        ///	&lt;/Robot&gt;
        ///	&lt;Robot&gt;
        ///		&lt;DisplayName&gt;Lynx Robot 2&lt;/DisplayName&gt;
        ///		&lt;HostName&gt;robot2.csem.flinders.edu.au&lt;/HostName&gt;
        ///		&lt;IPAddress&gt;&lt;/IPAddress&gt;
        ///	&lt;/Robot&gt;
        ///	&lt;Robot&gt;
        ///		&lt;DisplayName&gt;Lynx Robot 3&lt;/DisplayName&gt;
        ///		&lt;HostName&gt;robot3.csem.flinders.edu.au&lt;/HostName&gt;
        ///		&lt;IPAddress&gt;&lt;/IPAddress&gt;
        ///	&lt;/Robot&gt;
        ///	&lt;Robot&gt;
        ///		&lt;DisplayName&gt;Lynx Robot 4&lt;/DisplayName&gt;
        ///		&lt;HostName&gt;robo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Robots {
            get {
                return ResourceManager.GetString("Robots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Properties.
        /// </summary>
        public static string tabProperties {
            get {
                return ResourceManager.GetString("tabProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudocode.
        /// </summary>
        public static string tabSomethingElse {
            get {
                return ResourceManager.GetString("tabSomethingElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string toolbarOpen {
            get {
                return ResourceManager.GetString("toolbarOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string toolbarSave {
            get {
                return ResourceManager.GetString("toolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        public static string untitledFileName {
            get {
                return ResourceManager.GetString("untitledFileName", resourceCulture);
            }
        }
    }
}
